#!/usr/bin/env python3
"""Generate src/domain/wc_oui_table.inc from the official IEEE OUI registry.

Usage:
    curl -sSo oui.csv https://standards-oui.ieee.org/oui/oui.csv
    python3 tools/gen_oui_table.py oui.csv > src/domain/wc_oui_table.inc

The table maps a stable-MAC OUI (first three octets) to one of the vendors the app knows
about. It is intentionally bounded (CAP per vendor): the Flipper loads the whole FAP into
RAM, and phone makers randomize their MAC so their OUIs rarely surface in a probe anyway.
The result is a hint, not an exhaustive DB. Regenerate by re-running this script.
"""

import csv
import re
import sys

CAP = 64  # max OUIs kept per vendor; smaller vendors are kept whole

# org-name (IEEE registry) -> WcVendor enum. Anchored to avoid false hits (e.g. Intelbras).
VENDORS = [
    ("WcVendorApple", r"^Apple, Inc"),
    ("WcVendorSamsung", r"^Samsung Electronics"),
    ("WcVendorHuawei", r"^Huawei"),
    ("WcVendorXiaomi", r"Xiaomi"),
    ("WcVendorGoogle", r"^Google"),
    ("WcVendorIntel", r"^Intel Corp"),
    ("WcVendorDell", r"^Dell Inc|^Dell EMC|^Dell Technolog"),
    ("WcVendorMicrosoft", r"^Microsoft"),
    ("WcVendorEspressif", r"Espressif"),
    ("WcVendorRaspberryPi", r"Raspberry Pi"),
    ("WcVendorQualcomm", r"^Qualcomm"),
    ("WcVendorBroadcom", r"^Broadcom"),
]

# Hand-curated OUIs kept first for each vendor so a known-good entry is never dropped by CAP.
# Always kept, whatever the selection below does: these are the blocks the tests pin and the
# hardware this app is actually pointed at.
PRIORITY = {
    "WcVendorApple": ["3C22FB", "F01898", "A483E7"],
    "WcVendorSamsung": ["00166C", "5C0A5B", "781FDB"],
    "WcVendorHuawei": ["00E0FC", "4846FB"],
    "WcVendorXiaomi": ["286C07", "640980", "34CE00"],
    "WcVendorGoogle": ["001A11", "3C5AB4", "F4F5E8"],
    "WcVendorIntel": ["001B21", "3413E8", "3CA9F4"],
    "WcVendorDell": ["001422", "180373"],
    "WcVendorMicrosoft": ["281878"],
    "WcVendorEspressif": ["240AC4", "A4CF12", "7CDFA1", "004B12"],
    "WcVendorRaspberryPi": ["B827EB", "DCA632", "E45F01", "D83ADD"],
    "WcVendorBroadcom": ["0005B5"],
}


def main():
    rows = list(csv.reader(open(sys.argv[1], encoding="utf-8", errors="replace")))[1:]
    by_org = [(r[1].upper(), r[2]) for r in rows if len(r) > 2 and re.fullmatch(r"[0-9A-Fa-f]{6}", r[1])]

    print("// Generated by tools/gen_oui_table.py from the IEEE OUI registry. Do not edit by hand.")
    print("// Regenerate: python3 tools/gen_oui_table.py oui.csv > src/domain/wc_oui_table.inc")
    total = 0
    for enum, pat in VENDORS:
        rx = re.compile(pat)
        matches = sorted({oui for oui, org in by_org if rx.search(org)})
        prio = [o for o in PRIORITY.get(enum, []) if o in matches]
        rest = [o for o in matches if o not in prio]
        # The most recent assignments, never the first. The list is sorted by OUI, which tracks
        # assignment age, so taking the head kept only each vendor's oldest blocks and missed
        # every modern phone and laptop. Measured on a sample of current hardware, taking the
        # tail doubles the hit rate at exactly the same table size; raising CAP beyond this
        # bought nothing, and the table is resident in RAM for the life of the app.
        take = max(0, CAP - len(prio))
        kept = prio + (rest[-take:] if take else [])
        for oui in kept:
            b = f"0x{oui[0:2]}, 0x{oui[2:4]}, 0x{oui[4:6]}"
            print(f"    {{{{{b}}}, {enum}}},")
        total += len(kept)
    print(f"// {total} entries", file=sys.stderr)


if __name__ == "__main__":
    main()
